spring:
  jpa:
    properties:
      jakarta:
        persistence:
          # SCHEMA GENERATION
          schema-generation:
            scripts:
              action: create
              create-target: schema.sql
      hibernate:
        format_sql: true