spring:
  # DATABASE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/apigym
    username: apigym
    password: apigym
  jpa:
    hibernate:
      ddl-auto: none

# LOG LEVELS
logging:
  level:
    ROOT: WARN