spring:
  # ANSI IN LOGS
  output:
    ansi:
      enabled: ALWAYS
  # DATABASE
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none

# LOG LEVELS
logging:
  level:
    ROOT: INFO
    n1b3lung0.apiGym: DEBUG